### ISSUE TITLE
ImportError: No module named gcal.hooks

### ISSUE THREAD

**Issue by kossanah** [indictranstech/GCAL#12]
I tested with lastest erp VM
erpnext 6.16.2
frappe 6.17.3

frappe@erpnext:~/frappe-bench$ bench install-app gcal
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(_args, *_kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(_args, *_kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, *_kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), _args, *_kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands.py", line 163, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 93, in install_app
    app_hooks = frappe.get_hooks(app_name=name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 701, in get_hooks
    hooks = _dict(load_app_hooks(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 674, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/**init**.py", line 590, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named gcal.hooks
frappe@erpnext:~/frappe-bench$

**Comment by kossanah** [comment]
I have fixed this after I uninstalled old one and reinstall.

frappe@erpnext:~/frappe-bench/apps$ ls
erpnext  erpnext_demo  erpnext_shopify  frappe  gcal  paypal_integration
frappe@erpnext:~/frappe-bench/apps$ sudo rm -r gcal
frappe@erpnext:~/frappe-bench/apps$ ls
erpnext  erpnext_demo  erpnext_shopify  frappe  paypal_integration
frappe@erpnext:~/frappe-bench/apps$ cd ..
frappe@erpnext:~/frappe-bench$ bench get-app gcal https://github.com/indictranstech/GCAL.git
Cloning into 'gcal'...
remote: Counting objects: 35, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 35 (delta 0), reused 21 (delta 0), pack-reused 0
Unpacking objects: 100% (35/35), done.
Checking connectivity... done.
installing gcal
Wrote ./assets/js/print_format_v3.min.js - 18k
Wrote ./assets/js/frappe-web.min.js - 269k
Wrote ./assets/js/form.min.js - 106k
Wrote ./assets/js/report.min.js - 155k
Wrote ./assets/js/erpnext.min.js - 35k
Wrote ./assets/css/list.min.css - 6k
Wrote ./assets/js/erpnext-web.min.js - 1k
Wrote ./assets/css/report.min.css - 7k
Wrote ./assets/css/frappe-web.css - 51k
Wrote ./assets/js/list.min.js - 65k
Wrote ./assets/js/desk.min.js - 867k
Wrote ./assets/css/form.min.css - 2k
Wrote ./assets/js/editor.min.js - 26k
Wrote ./assets/css/erpnext.css - 1k
Wrote ./assets/css/desk.min.css - 256k
Wrote ./assets/js/module.min.js - 5k
Wrote ./assets/css/module.min.css - 1k
frappe-web: stopped
frappe-workerbeat: stopped
frappe-worker: stopped
frappe-worker: started
frappe-web: started
frappe-workerbeat: started
